# Generated by Django 3.2.24 on 2024-02-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryanswer',
            name='clean_text',
            field=models.CharField(default='', max_length=255, verbose_name='Ответ (если запрос без текста)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='queryanswer',
            name='pattern',
            field=models.CharField(max_length=255, verbose_name='Шаблон ответа (текст запроса помечается как {text})'),
        ),
    ]
