# Generated by Django 3.2.24 on 2024-02-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0002_auto_20240222_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name='Картинка'),
        ),
    ]
