# Generated by Django 3.2.24 on 2024-02-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0004_auto_20240222_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='is_daily',
            field=models.BooleanField(default=False),
        ),
    ]
