# Generated by Django 3.2.24 on 2024-02-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0005_query_is_daily'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='description_pattern',
            field=models.CharField(default='', max_length=255, verbose_name='Шаблон описания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='query',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Описание (если запрос без текста)'),
        ),
        migrations.AlterField(
            model_name='query',
            name='is_daily',
            field=models.BooleanField(default=False, verbose_name='У запроса одинаковый результат раз в день'),
        ),
    ]
