# Generated by Django 3.2.24 on 2024-02-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_id', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('has_blocked_bot', models.BooleanField(default=False)),
                ('last_action_datetime', models.DateTimeField(blank=True, null=True)),
                ('language', models.CharField(blank=True, choices=[('EN', 'en'), ('RU', 'ru')], default=None, max_length=2, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
